### ISSUE TITLE
Allow register domain with given uuid

### ISSUE THREAD

**Issue by zedongh** [cadence-workflow/cadence#5350]
**Is your feature request related to a problem? Please describe.**
No

**Proposed Solution**
register domain request support optional domain id parameter.

**Additional context**
Our cadence server running both old and latest version without xdc, to give user the fixed api workflow interface, it's convenient to keep same domain uuid for both system.

**Comment by ibarrajo** [comment]
I was approached by a contributor for first steps onto this issue, it would be good to share some guidance onto who tackles this issue.

Cadence in a multi cluster environment, domains have a unique UUID even if they share the same name. At Uber for example, we have a couple of regions. PHX and DCA. So a global domain would be created, say "cadence-samples-domain". A global domainis essentially the same domain name under the two regions (PHX and DCA) which are configured to function as Active and Passive for purposes of replication. Both instances of the cadence service would automatically generate a domain UUID when the domain is registered using the CLI with `cadence --do test-domain domain register --global_domain true`

We don't provide a mechanism to use a specific UUID during registration, but I imagine it would not be hard to create. Now what I definitely do not know is if Cadence depends on the UUID for replicating workflow history or in any way requires domains to have a unique domain UUID. I would suggest grepping the codebase to find out where and how the domain UUID is used.

**Comment by 3vilhamster** [comment]
This can cause issues when you have two domains with the same ID on two different clusters. Connecting them will cause big problems.
We need very good clarification on the problem you want to address.

DomainID is not exposed to the client, so it is purely internal to Cadence backend, what is the problem of having different IDs?

**Comment by demirkayaender** [comment]
@zedongh could you explain what you are trying to do and where/how you use domain id?

**Comment by zedongh** [comment]
> @zedongh could you explain what you are trying to do and where/how you use domain id?

This issue could be closed now. We have different version Cadence last year. One of them is very old version without xdc. For easily upgrade and unify user's interface. Wanna keep both version have same domain uuid (in two different cadence store).
