### ISSUE TITLE
Cadence v1.2.14 release doesn't publish any image

### ISSUE THREAD

**Issue by LauVietVan** [cadence-workflow/cadence#6541]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: `v1.2.14`
- Client version:
- Client langauge:

**Describe the bug**
The latest version `v1.2.14` is released without publishing the image to Dockerhub. The corresponding build that publish the image has failed: https://github.com/cadence-workflow/cadence/actions/runs/11823855535.
**To Reproduce**
Is the issue reproducible? 
- Yes 

**Steps to reproduce the behavior:**
Release a new version or rerun the failed `Publish Docker `image workflow will not publish any image.

**Expected behavior**

The image `ubercadence/server:v1.2.14` is published to the Dockerhub https://hub.docker.com/r/ubercadence/server.

**Screenshots**

**Additional context**
Add any other context about the problem here, E.g. Stackstace, workflow history.

**Comment by jakobht** [comment]
Hi! Thank you for reporting this!
I will prioritize pushing these images tomorrow (CET).

**Comment by jakobht** [comment]
Thanks again for the report, I have pushed the images now.
